### ISSUE TITLE
Interesting Interface

### ISSUE THREAD

**Issue by MikhadziukAliaksei** [DelauEnd/CargoTransportationAPI#9]
![image](https://user-images.githubusercontent.com/69195770/150399620-5f078cb7-1738-40ba-8d5c-2f00dd4ccb63.png)
Why do we need an empty interface?

**Comment by DelauEnd** [comment]
> ![image](https://user-images.githubusercontent.com/69195770/150399620-5f078cb7-1738-40ba-8d5c-2f00dd4ccb63.png) Why do we need an empty interface?

**Comment by DelauEnd** [comment]
i created this interface to unite all entity models
